spring:
  application:
    name: vra-poc00-kotlin
  flyway:
    enabled: false
  sql:
    init:
      mode: never
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      accept-float-as-int: false
      fail-on-null-for-primitives: true
server:
  address: 127.0.0.1
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
    include-exception: false
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
logging:
  structured:
    format:
      console: logstash
